[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.3.1"
  export = ["getinvoice_data_map"]
  icon = "docs/icon.png"
  keywords = ["Kind/Sample","Type/Service","Category/Service","Internal/http"]
  name = "getinvoice_data_map"
  org = "squidroll"
  version = "3.1.1"

